### ISSUE TITLE
Proposal: option to delete event in case of immediate reversion

### ISSUE THREAD

**Issue by gustavopch** [nxcd/paradox#16]
Context
---

In Trello.com, you can see the history of changes to the cards. If you change a card from one stack to another, you will see the change logged in the history ("Card X moved from stack A to stack B").

But if you immediately bring the card back to stack A (reversing the previous event), Trello **WON'T** show you the two events:
- "Card X moved from stack A to stack B"
- "Card X moved from stack B to stack A"

Instead, it will simply delete the first event. **Important to note** that it'll only have this behavior if the second event reverts the first one **in a very short period**. The argument would be: this prevents polluting the event history.

Proposal
---
I think Paradox could enable this behavior too. Of course, in some cases, this behavior would be undesired (e.g. I want every `product-price-was-changed` logged no matter what). So each event would have an option like `allowDeletingOnImmediateReversion` (or maybe a shorter name :smile:) to granularly enable/disable it.

It would be like the following:
- Given:
  - the current event causes the state to be equal to the previous state.
  - it's the same user that generated both current and previous events.
  - the difference in the events' timestamps is below 1 minute.
  - the event has `allowDeletingOnImmediateReversion` set to `true`.
- Then:
  - don't add the current event to `events`.
  - delete the previous event.

Real-world scenario
---
I have a list of products, each one has a `position` property that determines the sorting on the UI. I can drag-n-drop the products to reorder them. If I drag-n-drop a product and then **immediately** bring it back to the previous position, it was certainly a mistake and there's absolutely no value in logging two `product-position-was-changed` events for this mistake.

**Comment by khaosdoctor** [comment]
Hey! Sorry about the delay in answering your PR.

So, about your idea, it is indeed a great idea. However I don't see how Paradox would be responsible for these scenarios. In my view, Paradox should be really dumb, the intent of this library is to be a helper to abstract event sourcing functionalities.

This problem you're proposing is, indeed, a real occurrence in many real world cases, however, deleting an event is somehow an "anti-pattern" of event sourcing, since the whole point is to have the **whole** history of events, even those that were undone (even in a short period of time).

Besides, this is a project/application decision, in my opinion, the developer should be the one responsible for implementing this sort of functionality, since, as I said earlier, this lib is just intended to be a helper/scaffold for building on top of this architecture.

---

Switching subjects, my suggestion to you in this kind of scenario is not to save on the `positionChanged` event, but implement a "save" button or a timeout to send the `save` request. This would prevent your backend from saving quick events and also would make your event repository cleaner.

Thanks for the heads up though! 😄 those discussions are always welcome!

**Comment by gustavopch** [comment]
That makes sense.

---

In the end I've changed the `position` field to be present only in the state of the doc. My repository does the following:
```ts
new Product().setPersistedEvents(doc.events).setPosition(doc.state.position)
```

I'm not entirely sure whether by doing this (i.e. depending on a prop extracted directly from  `doc.state` instead of the reduced state) I'm depending on an implementation detail that's subject to changes. Anyway I would go as far as creating another collection/entity just to have the `position` without event sourcing.

When I change, let's say, product at position 3 to position 6, this is what happens:
- position 4 -> position 3
- position 5 -> position 4
- position 6 -> position 5
- position 3 -> position 6

Now imagine going from position 3 to 35. Each involved doc would be added an event: 33 events total for something I really don't care and don't need to audit. :smile: 

This approach is working fine for me.

**Comment by khaosdoctor** [comment]
Well, it is a possibility, but this is going to give you a really bad headache in the future. Imagine this:

- You set the state directly (not through an event) 

This means that the entity has no way to know this field is set, so when you reduce the state this field will not be present and you'll have to add it manually at every reduce. This is against the pattern and, eventually, will cause you problems.

--- 

We had this same exact problem in one of your systems. Our solution was to send the **entire** position array to the event. So let's imagine your situation here:

```
* position 4 -> position 3
* position 5 -> position 4
* position 6 -> position 5
* position 3 -> position 6
```

Instead of updating the the positions one by one, we'd send and request with all positions:

```js
items = [
  { itemId: xxx, position: 3 },
  { itemId: xxx, position: 4 }
]
```

And so on...

This updates the **whole** state instead of only a single event. And, since it is only a single event, this is atomic and updates the whole state of the application, thus, rendering unnecessary the action of updating all the positions one by one.

**Comment by gustavopch** [comment]
My state getter is as follows:
```ts
get state() {
  const reducedState = this.reducer.reduce(new Product(), [...this.persistedEvents, ...this.pendingEvents])

  return {
    ...
    position: this.position,
    ...
  }
}
```

I didn't quite understand your solution. Each product has it's own `position`. If I need to update multiple product positions, then I must add one `product-was-repositioned` to each product. Do you keep the positions in a separated doc?

**Comment by khaosdoctor** [comment]
No, we kept the array of positions in the same entity. Maybe you'll need to keep the array of products and positions in the same entity

**Comment by gustavopch** [comment]
I think the situation you described may be different from mine.

In my case, each product is a single entity that can only ever know its own `position`, never the position of any other product. Each product entity represents data like the following:
```ts
const product = {
  name: 'Coca-Cola 350ml'
  position: 0
}
```

I mean, the products are not all together in a single entity.

---

But now I thought I could indeed have a separate entity called "Listing" that would be like:
```ts
const listing = {
  name: 'Home Page Listing',
  content: [
    // Following would be the ordered IDs
    '61b119fb3b63d3760c20c62b',
    'eaec7587ffa90d651b62990d',
    '502949dff4424f7470c736b5',
    'df2bfca93d7477dc0a098e4c',
    'bfaeabd916a3dd804a72ebc6'
  ]
}
```

In my client, I would fetch the listing and products and use the ordered IDs to do the sorting for the UI.

**Comment by rjmunhoz** [comment]
Actually, @gustavopch, I think you situation is really similar to ours.
I believe what @khaosdoctor meant was that we don't update our items as they're moved from one position to another.

We have, like @khaosdoctor said before, a "Save" button on the UI, that sends all the items and positions. Then, we update each one individually, but only once, and use `bulkUpdate` to update them in the database.

This way, we avoid polluting the events array of our items, as well as reduce the number of calls our APIs (and thus, database) receives.

**Comment by gustavopch** [comment]
@rjmunhoz If I understand correctly, you end up having 1 new `e:sequence-was-changed` added to each item. So that's exactly what I was doing. If you change item at position 3 to position 35, each item gets a new event (total of events added to the database thus being 33).

I don't know your specific use-case, but for me this information would cause nothing but useless data added to the event history of the individual products. Now, it does make more sense to have a Listing entity containing all the IDs in the desired order (as the example in my previous comment). With this approach, even if product at position 3 went to position bazillion, a single entity (the Listing) would receive a single event (`listing-was-updated`).

**Comment by rjmunhoz** [comment]
@gustavopch Sure, but, the way your doing it know causes all the affected products to have 33 events each 😅

---

Indeed, it does work if you have a listing entity, though I'm not sure if that would or would not generate unnecessary overhead.

---

Anyway, do let us know what you decide at the end. It's always good to exchange ideas 😃

**Comment by gustavopch** [comment]
@rjmunhoz Not really. I was adding a single event to each affected product, just like you. That's 33 events total, not 33 to each item (that would be total madness :smile:).

The listing would be a trade-off: on the one hand some lines of code added to the project, on the other hand less events in the database and less separated events in the history. I mean: if all the position changes happen together, it may be fair to have them all visible at a glance in a single `listing-was-updated` event instead of having it spread out among tens or hundreds of entities.

Thanks for you considerations. :smiley:
