### ISSUE TITLE
EventEntity should not have an index signature

### ISSUE THREAD

**Issue by gustavopch** [nxcd/paradox#5]
I think EventEntity class should not declare an index signature. It gives room for typos.

Imagine the following entity:
```ts
class Shop extends EventEntity<Shop> {
  ...
  zip: string | null = null
}
```
Then we have an event that tries to update `zipCode` instead of `zip`, maybe because once before that property was called like that, but we forgot to change this piece of code:
```ts
class ShopZipChanged extends Event<{IShopZipChangeParams}> {
  ...
  static commit(state: Shop, event: ShopZipChanged) {
    // It should be: state.zip = event.data.name
    state.zipCode = event.data.name
  }
}
```
Because EventEntity declared an index signature, the linter and the compiler won't catch anything wrong here.

**Comment by khaosdoctor** [comment]
What do you call an index signature?

**Comment by gustavopch** [comment]
This line on the `EventEntity.ts`:
```ts
  [key: string]: any
```
It should be removed to prevent the user from acessing non-existent properties at the entity.

**Comment by khaosdoctor** [comment]
Oh yes! This was not meant to be there anymore, it's a remain of an old implementation. Thanks for the heads up!

**Comment by gustavopch** [comment]
For the library perspective, the index signature avoids the compilation error you mentioned, but from the user perspective, he's able to access properties that don't exist in the entity (like `shop.jkljfkdjfdlk`) without getting any error.

**Comment by khaosdoctor** [comment]
Yeah but this is due to the dynamic nature of Javascript itself. We're not dealing with a typed language... It is still Javascript no matter what we do to type it. If we protect the user by, let's say, adding a new generic or marking index signatures something like:

```ts
type Union = EventEntity | T;

class EventEntity<T> {
 [key: Union]: any
}
```

Which might be a solution but I'd have to test it. Still, in the end of the day, for Javascript users who download this lib, they'll still be able to access properties they shouldn't. So the solution was good, but aimed at a specific user type.

**Comment by rjmunhoz** [comment]
Reopening this since I think we completely overlooked it.
We, ourselves, are that specific kind of users, so this could become a shot on our own foot.

I'll PR with a fix soon.

Thanks for pointing that out, @gustavopch :D
