### ISSUE TITLE
Recalculate currentState inside EventEntity's `updateState`

### ISSUE THREAD

**Issue by rjmunhoz** [nxcd/paradox#9]
Currently, we rely on the state returned by the `state` getter, but that is innaccurate, since properties that are not exposed (and thus not returned by the getter) will never be updated.

Also, `state` getter has an `any` return type, which means it could set new properties that are only part of the representation of the final state, and not the state itself

**Comment by gustavopch** [comment]
Does it mean we don't need to implement the state getter anymore? :thinking:

**Comment by khaosdoctor** [comment]
No, the getter is still needed if you want to return the object implementation of the entity.

This approach was to split the data the user wants to return from the data the entity has. For instance, an user object: It has a `password` field, which is part of the entity, but we don't want to return it in the state object. However, if this object is not in the state, it is not updated by the `updateState` function and thus, things get out of control. Since some unwanted side effects happened in #10 then we had to rollback everything.

The point is to give the user the ability to return only the properties they want regardless of the state object.
